# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

# Use config.yml values for some configuration.
require 'yaml'
unless File.exist?("config.yml")
  raise 'Configuration (config.yml) file not found.'
end
vconfig = YAML.load_file("config.yml")

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "debian/jessie64"
  config.vm.box = "centos/7"
  config.ssh.insert_key = false

  # Set order so virtualbox provider is used unless overridden.
  config.vm.provider "virtualbox"
  config.vm.provider "vmware_fusion"

  # NiFi Toolkit 1.
  config.vm.define "nftk1" do |nftk1|
    nftk1.vm.network :private_network, ip: "192.168.77.4"

    # VirtualBox.
    nftk1.vm.hostname = "nftk1." + vconfig['site_url']
    nftk1.vm.provider :virtualbox do |v|
      v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      v.name = "nftk1." + vconfig['site_url']
      v.memory = 1024
      v.cpus = 1
    end
  end



  # NiFi 1.
  config.vm.define "nf1" do |nf1|
    nf1.vm.network :private_network, ip: "192.168.77.5"

    # VirtualBox.
    nf1.vm.hostname = "nf1." + vconfig['site_url']
    nf1.vm.provider :virtualbox do |v|
      v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
      v.name = "nf1." + vconfig['site_url']
      v.memory = 1024
      v.cpus = 1
    end

    # Run ansible provisioner for all VMs at the end.
    nf1.vm.provision "ansible" do |ansible|
      ansible.playbook = "../../playbooks/main.yml"
      ansible.inventory_path = "../../inventory"
      ansible.limit = "all"
    end
  end

end
